version: '3'
services:
  blogging-db:
    container_name: blogging-db
    image: postgres:10.6-alpine
    environment:
      - 'POSTGRES_DB=blogging_db'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'
